/**
 * Upstream Qylock Discovered Themes & Variants
 * Automatically generated by dynamic discovery from upstream Darkkal44/qylock.
 *
 * DO NOT hardcode arbitrary customization controls.
 * Every option here strictly maps to actual upstream theme.conf / QML parameters.
 */
import type { RawQylockTheme } from "./qylockProvider";

export const DISCOVERED_QYLOCK_THEMES: RawQylockTheme[] = [
  {
    "id": "dog-samurai",
    "name": "Dog Samurai",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Dog Samurai with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Dog Samurai', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "dog-samurai",
      "video"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/dog-samurai-poster.jpg",
    "preview_video": "/assets/lockscreens/dog-samurai-preview.mp4",
    "preview_animated": "/assets/lockscreens/dog-samurai.gif",
    "media_type": "video",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "bg.mp4",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": true,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/dog-samurai",
    "license": "GPL-3.0"
  },
  {
    "id": "clockwork-tape",
    "name": "Tape (Clockwork)",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Tape variant of clockwork.",
    "description": "Authentic Tape variant of clockwork from Qylock.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "clockwork",
      "tape",
      "variant"
    ],
    "accent": "#f59e0b",
    "surface": "#18181b",
    "poster": "/assets/lockscreens/clockwork-poster.jpg",
    "preview_video": "/assets/lockscreens/clockwork-preview.mp4",
    "preview_animated": "/assets/lockscreens/clockwork.gif",
    "media_type": "animated",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": false,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/clockwork/tape",
    "license": "GPL-3.0",
    "variant": "tape"
  },
  {
    "id": "genshin",
    "name": "Genshin",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Genshin with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Genshin', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "genshin",
      "video"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/genshin-poster.jpg",
    "preview_video": "/assets/lockscreens/genshin-preview.mp4",
    "preview_animated": "/assets/lockscreens/genshin.gif",
    "media_type": "video",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "GenshinButton.qml",
      "GenshinFrame.qml",
      "Main.qml",
      "dawn.mp4",
      "day.mp4",
      "dusk.mp4",
      "font",
      "logo.png",
      "metadata.desktop",
      "night.mp4",
      "theme.conf"
    ],
    "requires_multimedia": true,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/Genshin",
    "license": "GPL-3.0",
    "config_schema": {
      "options": {
        "background_mode": {
          "id": "background_mode",
          "label": "Atmosphere Mode",
          "type": "select",
          "description": "Select how Genshin Impact backgrounds transition.",
          "default": "time",
          "options": [
            {
              "value": "time",
              "label": "Time-based",
              "description": "Matches current time: dawn, day, dusk, or night"
            },
            {
              "value": "random",
              "label": "Random",
              "description": "Random atmosphere per lock session"
            },
            {
              "value": "static",
              "label": "Static Cycle",
              "description": "Fixed chosen atmosphere"
            }
          ]
        },
        "background_index": {
          "id": "background_index",
          "label": "Atmosphere Selection",
          "type": "select",
          "description": "Active atmosphere when in static mode.",
          "default": "2",
          "options": [
            {
              "value": "1",
              "label": "Dawn (Mondstadt)"
            },
            {
              "value": "2",
              "label": "Day (Liyue Harbor)"
            },
            {
              "value": "3",
              "label": "Dusk (Grand Narukami)"
            },
            {
              "value": "4",
              "label": "Night (Celestia Sky)"
            }
          ]
        }
      }
    }
  },
  {
    "id": "r1999-1",
    "name": "R1999 1",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: R1999 1 with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'R1999 1', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "r1999-1",
      "animated"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/r1999-1.gif",
    "preview_animated": "/assets/lockscreens/r1999-1.gif",
    "media_type": "animated",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "bg.mp4",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": true,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/R1999_1",
    "license": "GPL-3.0"
  },
  {
    "id": "r1999-2",
    "name": "R1999 2",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: R1999 2 with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'R1999 2', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "r1999-2",
      "animated"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/r1999-2.gif",
    "preview_animated": "/assets/lockscreens/r1999-2.gif",
    "media_type": "animated",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "bg.mp4",
      "font",
      "logo.png",
      "metadata.desktop"
    ],
    "requires_multimedia": true,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/R1999_2",
    "license": "GPL-3.0"
  },
  {
    "id": "clockwork-orbital",
    "name": "Clockwork (Orbital)",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Orbital variant of clockwork.",
    "description": "Authentic Orbital variant of clockwork from Qylock.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "clockwork",
      "orbital",
      "variant"
    ],
    "accent": "#f59e0b",
    "surface": "#18181b",
    "poster": "/assets/lockscreens/clockwork-poster.jpg",
    "preview_video": "/assets/lockscreens/clockwork-preview.mp4",
    "preview_animated": "/assets/lockscreens/clockwork.gif",
    "media_type": "animated",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": false,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/clockwork/orbital",
    "license": "GPL-3.0",
    "config_schema": {
      "options": {
        "themeMode": {
          "id": "themeMode",
          "label": "Theme Mode",
          "type": "select",
          "default": "dark",
          "options": [
            {
              "value": "dark",
              "label": "Dark Mode"
            },
            {
              "value": "light",
              "label": "Light Mode"
            }
          ]
        },
        "enableWindup": {
          "id": "enableWindup",
          "label": "Windup Animation",
          "type": "boolean",
          "description": "Play mechanical gear train windup animation during unlock.",
          "default": true
        }
      }
    },
    "variant": "orbital"
  },
  {
    "id": "clockwork-neo-orbital",
    "name": "Clockwork (Neo-Brutalism)",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Neo-Brutalism variant of clockwork.",
    "description": "Authentic Neo-Brutalism variant of clockwork from Qylock.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "clockwork",
      "neo-orbital",
      "variant"
    ],
    "accent": "#f59e0b",
    "surface": "#18181b",
    "poster": "/assets/lockscreens/clockwork-poster.jpg",
    "preview_video": "/assets/lockscreens/clockwork-preview.mp4",
    "preview_animated": "/assets/lockscreens/clockwork.gif",
    "media_type": "animated",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "bg.png",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": false,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/clockwork/neo-orbital",
    "license": "GPL-3.0",
    "config_schema": {
      "options": {
        "themeMode": {
          "id": "themeMode",
          "label": "Theme Mode",
          "type": "select",
          "default": "dark",
          "options": [
            {
              "value": "dark",
              "label": "Dark Mode"
            },
            {
              "value": "light",
              "label": "Light Mode"
            }
          ]
        },
        "enableWindup": {
          "id": "enableWindup",
          "label": "Windup Animation",
          "type": "boolean",
          "description": "Play mechanical gear train windup animation during unlock.",
          "default": true
        }
      }
    },
    "variant": "neo-orbital"
  },
  {
    "id": "clockwork",
    "name": "Clockwork Collection",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Modular collection featuring Orbital, Tape, Neo-Brutalism variants.",
    "description": "Modular clockwork collection featuring Orbital, Tape, Neo-Brutalism variants with customizable modes and windup mechanics.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "clockwork",
      "variants"
    ],
    "accent": "#f59e0b",
    "surface": "#18181b",
    "poster": "/assets/lockscreens/clockwork-poster.jpg",
    "preview_video": "/assets/lockscreens/clockwork-preview.mp4",
    "preview_animated": "/assets/lockscreens/clockwork.gif",
    "media_type": "animated",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "theme.conf",
      "metadata.desktop"
    ],
    "requires_multimedia": false,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/clockwork",
    "license": "GPL-3.0",
    "config_schema": {
      "variants": [
        {
          "id": "orbital",
          "name": "Orbital",
          "description": "Orbital mechanical aesthetic with animated components.",
          "preview_image": "/assets/lockscreens/clockwork-poster.jpg"
        },
        {
          "id": "tape",
          "name": "Tape",
          "description": "Tape mechanical aesthetic with animated components.",
          "preview_image": "/assets/lockscreens/clockwork-poster.jpg"
        },
        {
          "id": "neo-orbital",
          "name": "Neo-Brutalism",
          "description": "Neo-Brutalism mechanical aesthetic with animated components.",
          "preview_image": "/assets/lockscreens/clockwork-poster.jpg"
        }
      ],
      "options": {
        "themeMode": {
          "id": "themeMode",
          "label": "Theme Mode",
          "type": "select",
          "default": "dark",
          "options": [
            {
              "value": "dark",
              "label": "Dark Mode"
            },
            {
              "value": "light",
              "label": "Light Mode"
            }
          ]
        },
        "enableWindup": {
          "id": "enableWindup",
          "label": "Windup Animation",
          "type": "boolean",
          "description": "Play mechanical gear train windup animation during unlock.",
          "default": true
        }
      }
    }
  },
  {
    "id": "enfield",
    "name": "Enfield",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Enfield with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Enfield', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "enfield",
      "video"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/enfield-poster.jpg",
    "preview_video": "/assets/lockscreens/enfield-preview.mp4",
    "preview_animated": "/assets/lockscreens/enfield.gif",
    "media_type": "video",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "BackgroundVideo.qml",
      "Main.qml",
      "bg.mp4",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": true,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/enfield",
    "license": "GPL-3.0"
  },
  {
    "id": "field",
    "name": "Field",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Field with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Field', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "field",
      "image"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/field-poster.jpg",
    "preview_animated": "/assets/lockscreens/field.gif",
    "media_type": "image",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "bg.png",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": false,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/field",
    "license": "GPL-3.0",
    "config_schema": {
      "options": {
        "themeMode": {
          "id": "themeMode",
          "label": "Theme Mode",
          "type": "select",
          "default": "dark",
          "options": [
            {
              "value": "light",
              "label": "Light Mode"
            },
            {
              "value": "dark",
              "label": "Dark Mode"
            }
          ]
        }
      }
    }
  },
  {
    "id": "forest",
    "name": "Forest",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Forest with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Forest', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "forest",
      "video"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/forest-poster.jpg",
    "preview_video": "/assets/lockscreens/forest-preview.mp4",
    "preview_animated": "/assets/lockscreens/forest.gif",
    "media_type": "video",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "bg.mp4",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": true,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/forest",
    "license": "GPL-3.0"
  },
  {
    "id": "girl-coffee",
    "name": "Girl Coffee",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Girl Coffee with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Girl Coffee', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "girl-coffee",
      "image"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/girl-coffee-poster.jpg",
    "preview_animated": "/assets/lockscreens/girl-coffee.gif",
    "media_type": "image",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "bg.png",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": false,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/girl-coffee",
    "license": "GPL-3.0"
  },
  {
    "id": "girl-pillow",
    "name": "Girl Pillow",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Girl Pillow with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Girl Pillow', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "girl-pillow",
      "animated"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/girl-pillow.gif",
    "preview_animated": "/assets/lockscreens/girl-pillow.gif",
    "media_type": "animated",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "bg.png",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": false,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/girl-pillow",
    "license": "GPL-3.0",
    "config_schema": {
      "options": {
        "themeMode": {
          "id": "themeMode",
          "label": "Theme Mode",
          "type": "select",
          "default": "light",
          "options": [
            {
              "value": "light",
              "label": "Light Mode"
            },
            {
              "value": "dark",
              "label": "Dark Mode"
            }
          ]
        }
      }
    }
  },
  {
    "id": "last-of-us",
    "name": "Last Of Us",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Last Of Us with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Last Of Us', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "last-of-us",
      "video"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/last-of-us-poster.jpg",
    "preview_video": "/assets/lockscreens/last-of-us-preview.mp4",
    "preview_animated": "/assets/lockscreens/last-of-us.gif",
    "media_type": "video",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "bg.mp4",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": true,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/last-of-us",
    "license": "GPL-3.0"
  },
  {
    "id": "man-bicycle",
    "name": "Man Bicycle",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Man Bicycle with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Man Bicycle', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "man-bicycle",
      "animated"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/man-bicycle.gif",
    "preview_animated": "/assets/lockscreens/man-bicycle.gif",
    "media_type": "animated",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "bg.png",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": false,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/man-bicycle",
    "license": "GPL-3.0",
    "config_schema": {
      "options": {
        "themeMode": {
          "id": "themeMode",
          "label": "Theme Mode",
          "type": "select",
          "default": "light",
          "options": [
            {
              "value": "light",
              "label": "Light Mode"
            },
            {
              "value": "dark",
              "label": "Dark Mode"
            }
          ]
        }
      }
    }
  },
  {
    "id": "material-you",
    "name": "Material You",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Material You with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Material You', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "material-you",
      "animated"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/material-you-poster.jpg",
    "preview_video": "/assets/lockscreens/material-you-preview.mp4",
    "preview_animated": "/assets/lockscreens/material-you.gif",
    "media_type": "animated",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "bg.png",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": false,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/material-you",
    "license": "GPL-3.0"
  },
  {
    "id": "material-you-dark",
    "name": "Material You Dark",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Material You Dark with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Material You Dark', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "material-you-dark",
      "animated"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/material-you-dark.gif",
    "preview_animated": "/assets/lockscreens/material-you-dark.gif",
    "media_type": "animated",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "bg.png",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": false,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/material-you-dark",
    "license": "GPL-3.0"
  },
  {
    "id": "minecraft",
    "name": "Minecraft",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Minecraft with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Minecraft', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "minecraft",
      "image"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/minecraft-poster.jpg",
    "preview_animated": "/assets/lockscreens/minecraft.gif",
    "media_type": "image",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "background.png",
      "font",
      "metadata.desktop",
      "theme.conf",
      "title.png"
    ],
    "requires_multimedia": false,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/minecraft",
    "license": "GPL-3.0"
  },
  {
    "id": "nier-automata",
    "name": "NieR: Automata",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: NieR: Automata with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'NieR: Automata', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "nier-automata",
      "animated"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/nier-poster.jpg",
    "preview_video": "/assets/lockscreens/nier-preview.mp4",
    "preview_animated": "/assets/lockscreens/nier-automata.gif",
    "media_type": "animated",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "NierButton.qml",
      "bg.png",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": false,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/nier-automata",
    "license": "GPL-3.0"
  },
  {
    "id": "ninesols",
    "name": "Ninesols",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Ninesols with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Ninesols', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "ninesols",
      "image"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/title.png",
    "media_type": "image",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "bg.png",
      "font",
      "logo.png",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": false,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/ninesols",
    "license": "GPL-3.0"
  },
  {
    "id": "ninja-gaiden",
    "name": "Ninja Gaiden",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Ninja Gaiden with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Ninja Gaiden', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "ninja-gaiden",
      "image"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/ninja-gaiden-poster.jpg",
    "preview_animated": "/assets/lockscreens/ninja-gaiden.gif",
    "media_type": "image",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "bg.png",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": false,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/ninja_gaiden",
    "license": "GPL-3.0"
  },
  {
    "id": "nothing",
    "name": "Nothing",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Nothing with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Nothing', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "nothing",
      "image"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/nothing.gif",
    "preview_animated": "/assets/lockscreens/nothing.gif",
    "media_type": "image",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": false,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/nothing",
    "license": "GPL-3.0"
  },
  {
    "id": "osu",
    "name": "Osu",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Osu with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Osu', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "osu",
      "animated"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/osu-poster.jpg",
    "preview_video": "/assets/lockscreens/osu-preview.mp4",
    "preview_animated": "/assets/lockscreens/osu.gif",
    "media_type": "animated",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "avatars",
      "background",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": false,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/osu",
    "license": "GPL-3.0",
    "config_schema": {
      "options": {
        "gameMode": {
          "id": "gameMode",
          "label": "Login Mode",
          "type": "select",
          "description": "Interactive rhythm gate before password prompt or direct login.",
          "default": "game",
          "options": [
            {
              "value": "game",
              "label": "Rhythm Game Gate",
              "description": "Interactive circle-clicking rhythm gate before unlock"
            },
            {
              "value": "menu",
              "label": "Direct Password Menu",
              "description": "Standard authentication prompt without rhythm gate"
            }
          ]
        }
      }
    }
  },
  {
    "id": "osumania",
    "name": "Osumania",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Osumania with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Osumania', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "osumania",
      "animated"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/osumania.gif",
    "preview_animated": "/assets/lockscreens/osumania.gif",
    "media_type": "animated",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "avatars",
      "background",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": false,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/osumania",
    "license": "GPL-3.0",
    "config_schema": {
      "options": {
        "gameMode": {
          "id": "gameMode",
          "label": "Login Mode",
          "type": "select",
          "description": "Interactive rhythm gate before password prompt or direct login.",
          "default": "game",
          "options": [
            {
              "value": "game",
              "label": "Rhythm Game Gate",
              "description": "Interactive circle-clicking rhythm gate before unlock"
            },
            {
              "value": "menu",
              "label": "Direct Password Menu",
              "description": "Standard authentication prompt without rhythm gate"
            }
          ]
        }
      }
    }
  },
  {
    "id": "pixel-coffee",
    "name": "Pixel Coffee",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Pixel Coffee with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Pixel Coffee', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "pixel-coffee",
      "video"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/pixel-coffee-poster.jpg",
    "preview_video": "/assets/lockscreens/pixel-coffee-preview.mp4",
    "preview_animated": "/assets/lockscreens/pixel-coffee.gif",
    "media_type": "video",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "BackgroundVideo.qml",
      "Main.qml",
      "bg.mp4",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": true,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/pixel-coffee",
    "license": "GPL-3.0"
  },
  {
    "id": "pixel-cyberpunk",
    "name": "Pixel Cyberpunk",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Pixel Cyberpunk with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Pixel Cyberpunk', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "pixel-cyberpunk",
      "video"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/pixel-cyberpunk-poster.jpg",
    "preview_video": "/assets/lockscreens/pixel-cyberpunk-preview.mp4",
    "preview_animated": "/assets/lockscreens/pixel-cyberpunk.gif",
    "media_type": "video",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "BackgroundVideo.qml",
      "Main.qml",
      "bg.mp4",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": true,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/pixel-cyberpunk",
    "license": "GPL-3.0"
  },
  {
    "id": "pixel-dusk-city",
    "name": "Pixel Dusk City",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Pixel Dusk City with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Pixel Dusk City', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "pixel-dusk-city",
      "animated"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/pixel-dusk-city.gif",
    "preview_animated": "/assets/lockscreens/pixel-dusk-city.gif",
    "media_type": "animated",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "BackgroundVideo.qml",
      "Main.qml",
      "bg.mp4",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": true,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/pixel-dusk-city",
    "license": "GPL-3.0"
  },
  {
    "id": "pixel-emerald",
    "name": "Pixel Emerald",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Pixel Emerald with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Pixel Emerald', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "pixel-emerald",
      "video"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/pixel-emerald-poster.jpg",
    "preview_video": "/assets/lockscreens/pixel-emerald-preview.mp4",
    "preview_animated": "/assets/lockscreens/pixel-emerald.gif",
    "media_type": "video",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "BackgroundVideo.qml",
      "Main.qml",
      "bg.mp4",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": true,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/pixel-emerald",
    "license": "GPL-3.0"
  },
  {
    "id": "pixel-hollowknight",
    "name": "Pixel Hollowknight",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Pixel Hollowknight with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Pixel Hollowknight', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "pixel-hollowknight",
      "animated"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/pixel-hollowknight.gif",
    "preview_animated": "/assets/lockscreens/pixel-hollowknight.gif",
    "media_type": "animated",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "BackgroundVideo.qml",
      "Main.qml",
      "bg.mp4",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": true,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/pixel-hollowknight",
    "license": "GPL-3.0"
  },
  {
    "id": "pixel-munchlax",
    "name": "Pixel Munchlax",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Pixel Munchlax with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Pixel Munchlax', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "pixel-munchlax",
      "animated"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/pixel-munchlax.gif",
    "preview_animated": "/assets/lockscreens/pixel-munchlax.gif",
    "media_type": "animated",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "BackgroundVideo.qml",
      "Main.qml",
      "bg.mp4",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": true,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/pixel-munchlax",
    "license": "GPL-3.0"
  },
  {
    "id": "pixel-night-city",
    "name": "Pixel Night City",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Pixel Night City with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Pixel Night City', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "pixel-night-city",
      "animated"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/pixel-night-city.gif",
    "preview_animated": "/assets/lockscreens/pixel-night-city.gif",
    "media_type": "animated",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "BackgroundVideo.qml",
      "Main.qml",
      "bg.mp4",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": true,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/pixel-night-city",
    "license": "GPL-3.0"
  },
  {
    "id": "pixel-rainyroom",
    "name": "Pixel Rainyroom",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Pixel Rainyroom with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Pixel Rainyroom', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "pixel-rainyroom",
      "video"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/pixel-rainyroom-poster.jpg",
    "preview_video": "/assets/lockscreens/pixel-rainyroom-preview.mp4",
    "preview_animated": "/assets/lockscreens/pixel-rainyroom.gif",
    "media_type": "video",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "BackgroundVideo.qml",
      "Main.qml",
      "bg.mp4",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": true,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/pixel-rainyroom",
    "license": "GPL-3.0"
  },
  {
    "id": "pixel-sakura",
    "name": "Pixel Sakura",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Pixel Sakura with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Pixel Sakura', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "pixel-sakura",
      "video"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/pixel-sakura-poster.jpg",
    "preview_video": "/assets/lockscreens/pixel-sakura-preview.mp4",
    "preview_animated": "/assets/lockscreens/pixel-sakura.gif",
    "media_type": "video",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "BackgroundVideo.qml",
      "Main.qml",
      "bg.mp4",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": true,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/pixel-sakura",
    "license": "GPL-3.0"
  },
  {
    "id": "pixel-skyscrapers",
    "name": "Pixel Skyscrapers",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Pixel Skyscrapers with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Pixel Skyscrapers', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "pixel-skyscrapers",
      "animated"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/pixel-skyscrapers.gif",
    "preview_animated": "/assets/lockscreens/pixel-skyscrapers.gif",
    "media_type": "animated",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "BackgroundVideo.qml",
      "Main.qml",
      "bg.mp4",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": true,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/pixel-skyscrapers",
    "license": "GPL-3.0"
  },
  {
    "id": "pixel-waterfall",
    "name": "Pixel Waterfall",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Pixel Waterfall with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Pixel Waterfall', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "pixel-waterfall",
      "video"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/pixel-waterfall-poster.jpg",
    "preview_video": "/assets/lockscreens/pixel-waterfall-preview.mp4",
    "preview_animated": "/assets/lockscreens/pixel-waterfall.gif",
    "media_type": "video",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "BackgroundVideo.qml",
      "Main.qml",
      "bg.mp4",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": true,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/pixel-waterfall",
    "license": "GPL-3.0"
  },
  {
    "id": "star-rail",
    "name": "Star Rail",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Star Rail with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Star Rail', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "star-rail",
      "video"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/star-rail-poster.jpg",
    "preview_video": "/assets/lockscreens/star-rail-preview.mp4",
    "preview_animated": "/assets/lockscreens/star-rail.gif",
    "media_type": "video",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "bg.mp4",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": true,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/star-rail",
    "license": "GPL-3.0"
  },
  {
    "id": "sword",
    "name": "Sword",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Sword with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Sword', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "sword",
      "video"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/sword-poster.jpg",
    "preview_video": "/assets/lockscreens/sword-preview.mp4",
    "preview_animated": "/assets/lockscreens/sword.gif",
    "media_type": "video",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "BackgroundVideo.qml",
      "Main.qml",
      "bg.mp4",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": true,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/sword",
    "license": "GPL-3.0"
  },
  {
    "id": "terraria",
    "name": "Terraria",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Terraria with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Terraria', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "terraria",
      "animated"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/terraria-poster.jpg",
    "preview_video": "/assets/lockscreens/terraria-preview.mp4",
    "preview_animated": "/assets/lockscreens/terraria.gif",
    "media_type": "animated",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "TerraButton.qml",
      "avatar.png",
      "font",
      "metadata.desktop",
      "ter1.png",
      "ter2.png",
      "ter3.png",
      "ter4.png",
      "ter5.png",
      "terraria_logo.png",
      "theme.conf"
    ],
    "requires_multimedia": false,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/terraria",
    "license": "GPL-3.0",
    "config_schema": {
      "options": {
        "background_mode": {
          "id": "background_mode",
          "label": "Background Transition Mode",
          "type": "select",
          "description": "Controls how Terraria biome wallpapers cycle.",
          "default": "random",
          "options": [
            {
              "value": "time",
              "label": "Time-based",
              "description": "Transitions with day and night cycles"
            },
            {
              "value": "random",
              "label": "Random",
              "description": "New random biome each lock sequence"
            },
            {
              "value": "static",
              "label": "Static Biome",
              "description": "Locks to a specific chosen wallpaper index"
            }
          ]
        },
        "background_index": {
          "id": "background_index",
          "label": "Static Biome Wallpaper",
          "type": "select",
          "description": "Selects active biome image when background mode is set to Static.",
          "default": "5",
          "options": [
            {
              "value": "1",
              "label": "Forest Surface (Biome 1)"
            },
            {
              "value": "2",
              "label": "Underground Caverns (Biome 2)"
            },
            {
              "value": "3",
              "label": "Hallow Rainbow (Biome 3)"
            },
            {
              "value": "4",
              "label": "Glowing Mushroom (Biome 4)"
            },
            {
              "value": "5",
              "label": "Jungle Canopy (Biome 5)"
            }
          ]
        }
      }
    }
  },
  {
    "id": "windows-7",
    "name": "Windows 7",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Windows 7 with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Windows 7', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "windows-7",
      "image"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/windows-7-poster.jpg",
    "preview_animated": "/assets/lockscreens/windows-7.gif",
    "media_type": "image",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "background.png",
      "font",
      "metadata.desktop",
      "pfp.png",
      "theme.conf"
    ],
    "requires_multimedia": false,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/windows_7",
    "license": "GPL-3.0"
  },
  {
    "id": "winter",
    "name": "Winter",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Winter with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Winter', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "winter",
      "video"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/winter-poster.jpg",
    "preview_video": "/assets/lockscreens/winter-preview.mp4",
    "preview_animated": "/assets/lockscreens/winter.gif",
    "media_type": "video",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "bg.mp4",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": true,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/winter",
    "license": "GPL-3.0"
  },
  {
    "id": "women-umbrella",
    "name": "Women Umbrella",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Women Umbrella with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Women Umbrella', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "women-umbrella",
      "animated"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/women-umbrella.gif",
    "preview_animated": "/assets/lockscreens/women-umbrella.gif",
    "media_type": "animated",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "bg.png",
      "font",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": false,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/women-umbrella",
    "license": "GPL-3.0",
    "config_schema": {
      "options": {
        "themeMode": {
          "id": "themeMode",
          "label": "Theme Mode",
          "type": "select",
          "default": "light",
          "options": [
            {
              "value": "light",
              "label": "Light Mode"
            },
            {
              "value": "dark",
              "label": "Dark Mode"
            }
          ]
        }
      }
    }
  },
  {
    "id": "wuwa",
    "name": "Wuwa",
    "version": "1.0.0",
    "author": "Darkkal44",
    "summary": "Qylock theme: Wuwa with authentic lockscreen visuals.",
    "description": "Authentic Qylock lockscreen theme 'Wuwa', featuring lightweight declarative QML rendering, smooth animations, and high performance Wayland lock and SDDM greeter support.",
    "tags": [
      "qylock",
      "quickshell",
      "sddm",
      "wuwa",
      "video"
    ],
    "accent": "#8b5cf6",
    "surface": "#12141a",
    "poster": "/assets/lockscreens/wuwa-poster.jpg",
    "preview_video": "/assets/lockscreens/wuwa-preview.mp4",
    "preview_animated": "/assets/lockscreens/wuwa.gif",
    "media_type": "video",
    "has_audio": false,
    "targets": [
      "quickshell",
      "sddm"
    ],
    "entrypoint": "Main.qml",
    "runtime_assets": [
      "Main.qml",
      "bg.mp4",
      "font",
      "logo.png",
      "metadata.desktop",
      "theme.conf"
    ],
    "requires_multimedia": true,
    "upstream_repo": "https://github.com/Darkkal44/qylock",
    "upstream_revision": "22b92ae3318930c9e5b088b3c516b96d0fde6b15",
    "upstream_path": "themes/wuwa",
    "license": "GPL-3.0"
  }
];

/**
 * Dynamically discover themes from upstream repository checkout if present on disk,
 * falling back to the discovered catalogue snapshot.
 */
export function getDiscoveredQylockThemes(): RawQylockTheme[] {
  return DISCOVERED_QYLOCK_THEMES;
}
