# Aurora Glass Hyprlock
background {
    path = screenshot
    blur_passes = 2
    blur_size = 6
}
input-field {
    size = 200, 45
    outline_thickness = 2
    outer_color = rgb(34d399)
    inner_color = rgb(030712)
}
