//! Ryzora Hypridle Integration
//!
//! Manages the non-destructive integration between Ryzora's Quickshell lockscreen
//! and the user's hypridle idle daemon. This module:
//!
//! 1. Generates a Ryzora-managed hypridle config by parsing the user's existing config,
//!    preserving ALL listener blocks verbatim, and only changing `general.lock_cmd`.
//! 2. Records a SHA-256 hash of the source config to detect external changes (drift).
//! 3. Writes a systemd user service drop-in to redirect hypridle to Ryzora's config.
//! 4. Provides drift detection: if the source config changes while Ryzora is active,
//!    surfaces a warning rather than silently overwriting the user's changes.
//! 5. Writes the `ryzora-lock` wrapper script which safely dispatches to the active
//!    Ryzora lockscreen package or falls back to the previously-detected locker.
//!
//! SAFETY INVARIANTS:
//! - Never modifies `~/.config/hypr/hypridle.conf` or any Dusky-managed config.
//! - Never executes arbitrary package-provided scripts from `ryzora-lock`.
//! - Always uses validated Ryzora-owned entrypoints only.
//! - All integration artifacts are in Ryzora-owned directories.

use sha2::{Digest, Sha256};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/// The hypridle.conf source path that Ryzora reads (never modifies)
pub const HYPRIDLE_SOURCE_PATH: &str = ".config/hypr/hypridle.conf";
/// Ryzora's generated hypridle config path
pub const HYPRIDLE_RYZORA_CONFIG: &str = ".config/ryzora/hypridle.conf";
/// Ryzora's systemd user service drop-in path
pub const HYPRIDLE_DROPIN_PATH: &str =
    ".config/systemd/user/hypridle.service.d/ryzora-override.conf";
/// Ryzora's lock wrapper script path
pub const RYZORA_LOCK_PATH: &str = ".local/bin/ryzora-lock";
/// The host user lock script (used by Dusky Hyprland keybinds, Waybar, wlogout)
pub const USER_LOCK_SCRIPT_PATH: &str = "user_scripts/hyprlock/lock.sh";
/// Ryzora snapshot backup path for host user lock script
pub const USER_LOCK_SCRIPT_SNAPSHOT: &str =
    ".local/share/ryzora/snapshots/user_scripts_hyprlock_lock.sh";

#[derive(Debug, Clone)]
pub struct HypridleIntegrationStatus {
    pub lock_wrapper_exists: bool,
    pub lock_wrapper_path: PathBuf,
    pub ryzora_config_exists: bool,
    pub ryzora_config_path: PathBuf,
    pub dropin_exists: bool,
    pub dropin_path: PathBuf,
    pub hypridle_service_active: bool,
    pub source_hash: Option<String>,
    pub current_hash: Option<String>,
    pub drift_detected: bool,
}

/// Compute SHA-256 hex digest of a file
pub fn sha256_file(path: &Path) -> Option<String> {
    let data = fs::read(path).ok()?;
    let mut hasher = Sha256::new();
    hasher.update(&data);
    let result = hasher.finalize();
    Some(format!("{:x}", result))
}

/// Parse the user's hypridle.conf and generate a Ryzora version that:
/// - Preserves ALL listener { } blocks verbatim
/// - Replaces general.lock_cmd with the Ryzora lock wrapper path
/// - Preserves all other general { } fields verbatim
pub fn generate_ryzora_hypridle_config(
    source_path: &Path,
    ryzora_lock_path: &Path,
) -> Result<String, String> {
    let content = fs::read_to_string(source_path).map_err(|e| {
        format!(
            "Cannot read source hypridle config '{}': {}",
            source_path.display(),
            e
        )
    })?;

    let ryzora_lock_str = ryzora_lock_path
        .to_str()
        .ok_or("ryzora-lock path contains invalid UTF-8")?;

    let mut output = String::new();
    output.push_str("# =============================================================================\n");
    output.push_str("# Ryzora-managed hypridle configuration\n");
    output.push_str("# Generated by Ryzora — DO NOT EDIT\n");
    output.push_str("# Source: ");
    output.push_str(&source_path.display().to_string());
    output.push_str("\n");
    output.push_str("#\n");
    output.push_str("# This file replaces ONLY general.lock_cmd.\n");
    output.push_str("# All listener blocks and other settings are preserved from source.\n");
    output.push_str("# Remove the systemd drop-in at:\n");
    output.push_str("#   ~/.config/systemd/user/hypridle.service.d/ryzora-override.conf\n");
    output.push_str("# to restore original behavior.\n");
    output.push_str("# =============================================================================\n\n");

    // Parse the config: track whether we're in a `general { }` block
    let mut in_general_block = false;
    let mut brace_depth: i32 = 0;
    let mut lock_cmd_replaced = false;

    for line in content.lines() {
        let trimmed = line.trim();

        // Detect entry into `general { ` block
        if !in_general_block && brace_depth == 0 {
            if trimmed.starts_with("general") && trimmed.contains('{') {
                in_general_block = true;
                brace_depth = 1;
                output.push_str(line);
                output.push('\n');
                continue;
            }
        }

        if in_general_block {
            // Count braces
            for ch in trimmed.chars() {
                if ch == '{' {
                    brace_depth += 1;
                } else if ch == '}' {
                    brace_depth -= 1;
                }
            }

            if brace_depth == 0 {
                // Closing brace of general block
                in_general_block = false;
                // If we never saw lock_cmd, inject it before closing brace
                if !lock_cmd_replaced {
                    output.push_str(&format!(
                        "    lock_cmd = pidof quickshell || {}\n",
                        ryzora_lock_str
                    ));
                    lock_cmd_replaced = true;
                }
                output.push_str(line);
                output.push('\n');
                continue;
            }

            // Inside general block: replace lock_cmd
            if trimmed.starts_with("lock_cmd") && trimmed.contains('=') {
                // Replace with Ryzora lock command
                // Preserve leading whitespace
                let leading: String = line.chars().take_while(|c| c.is_whitespace()).collect();
                output.push_str(&format!(
                    "{}lock_cmd = pidof quickshell || {}\n",
                    leading, ryzora_lock_str
                ));
                lock_cmd_replaced = true;
                continue;
            }

            output.push_str(line);
            output.push('\n');
            continue;
        }

        // Outside general block — preserve verbatim (listener blocks, comments, etc.)
        output.push_str(line);
        output.push('\n');
    }

    // If no general block existed, add one
    if !lock_cmd_replaced {
        output.push_str("\ngeneral {\n");
        output.push_str(&format!("    lock_cmd = {}\n", ryzora_lock_str));
        output.push_str("}\n");
    }

    Ok(output)
}

/// Write the Ryzora lock wrapper script to `~/.local/bin/ryzora-lock`
pub fn write_ryzora_lock_wrapper(home: &Path) -> Result<PathBuf, String> {
    let bin_dir = home.join(".local/bin");
    fs::create_dir_all(&bin_dir)
        .map_err(|e| format!("Failed to create ~/.local/bin: {}", e))?;

    let lock_path = home.join(RYZORA_LOCK_PATH);
    let active_symlink = home.join(".local/share/ryzora/active/lockscreen/quickshell");
    let ryzora_lock_sh = home.join(".local/share/ryzora/integrations/quickshell/lock.sh");

    // NOTE: This wrapper NEVER executes arbitrary package-provided scripts.
    // It only calls the Ryzora-owned lock.sh written by ensure_quickshell_runtime_in().
    let script = format!(
        r#"#!/usr/bin/env bash
# Ryzora session-lock dispatcher — managed, do not edit
# Generated by Ryzora to integrate with hypridle's lock_cmd
RYZORA_ACTIVE="{active_symlink}"
RYZORA_LOCK="{ryzora_lock_sh}"

# Prevent duplicate instances
if pgrep -x quickshell > /dev/null 2>&1; then
    exit 0
fi

if [ -L "$RYZORA_ACTIVE" ] && [ -d "$RYZORA_ACTIVE" ] && command -v quickshell > /dev/null 2>&1; then
    # Ryzora-managed lockscreen — use validated Ryzora-owned entrypoint only
    if [ -f "$RYZORA_LOCK" ] && [ -x "$RYZORA_LOCK" ]; then
        exec "$RYZORA_LOCK"
    else
        echo "ryzora-lock: ERROR: Ryzora lock.sh not found or not executable at $RYZORA_LOCK" >&2
        # Fall through to system locker
    fi
fi

# Graceful fallback to system locker
if command -v hyprlock > /dev/null 2>&1; then
    exec hyprlock
elif command -v swaylock > /dev/null 2>&1; then
    exec swaylock
else
    echo "ryzora-lock: ERROR: No session locker available" >&2
    exit 1
fi
"#,
        active_symlink = active_symlink.display(),
        ryzora_lock_sh = ryzora_lock_sh.display(),
    );

    fs::write(&lock_path, &script)
        .map_err(|e| format!("Failed to write ryzora-lock wrapper: {}", e))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&lock_path, fs::Permissions::from_mode(0o755))
            .map_err(|e| format!("Failed to set ryzora-lock executable: {}", e))?;
    }

    Ok(lock_path)
}

/// Write the systemd user service drop-in for hypridle
pub fn write_hypridle_systemd_dropin(home: &Path) -> Result<PathBuf, String> {
    let dropin_dir = home.join(".config/systemd/user/hypridle.service.d");
    fs::create_dir_all(&dropin_dir)
        .map_err(|e| format!("Failed to create hypridle drop-in directory: {}", e))?;

    let dropin_path = home.join(HYPRIDLE_DROPIN_PATH);
    let ryzora_config = home.join(HYPRIDLE_RYZORA_CONFIG);

    // IMPORTANT: ExecStart= (empty) MUST come before the new value to reset it.
    // Without the empty reset, systemd would append to the existing ExecStart.
    let dropin_content = format!(
        r#"# Ryzora hypridle integration drop-in
# Generated by Ryzora — remove this file to restore default hypridle behavior
# Source: {dropin_path}
[Service]
ExecStart=
ExecStart=/usr/bin/hypridle -c {ryzora_config}
"#,
        dropin_path = dropin_path.display(),
        ryzora_config = ryzora_config.display(),
    );

    fs::write(&dropin_path, &dropin_content)
        .map_err(|e| format!("Failed to write hypridle drop-in: {}", e))?;

    Ok(dropin_path)
}

/// Reload and restart the hypridle user service, then verify exactly one instance runs.
/// In test mode (RYZORA_SYSTEM_ROOT set), skips the actual systemctl call.
pub fn reload_hypridle_service() -> Result<(), String> {
    if std::env::var("RYZORA_SYSTEM_ROOT").is_ok() {
        // Test mode: skip actual systemctl, just return Ok
        return Ok(());
    }

    // daemon-reload
    let reload = Command::new("systemctl")
        .args(["--user", "daemon-reload"])
        .status()
        .map_err(|e| format!("Failed to run systemctl daemon-reload: {}", e))?;
    if !reload.success() {
        return Err("systemctl --user daemon-reload failed".to_string());
    }

    // restart hypridle
    let restart = Command::new("systemctl")
        .args(["--user", "restart", "hypridle"])
        .status()
        .map_err(|e| format!("Failed to restart hypridle: {}", e))?;
    if !restart.success() {
        return Err(
            "systemctl --user restart hypridle failed — hypridle may not be installed".to_string(),
        );
    }

    // Verify service is active
    let status = Command::new("systemctl")
        .args(["--user", "is-active", "--quiet", "hypridle"])
        .status()
        .map_err(|e| format!("Failed to check hypridle status: {}", e))?;
    if !status.success() {
        return Err("hypridle service is not active after restart".to_string());
    }

    Ok(())
}

/// Apply the full hypridle integration for a Quickshell lockscreen:
/// 1. Write ryzora-lock wrapper
/// 2. Generate Ryzora hypridle config from source
/// 3. Write systemd drop-in
/// 4. Reload hypridle
///
/// Returns: (source_hash, ryzora_lock_path)
pub fn apply_hypridle_integration(home: &Path) -> Result<(String, PathBuf), String> {
    let source_path = home.join(HYPRIDLE_SOURCE_PATH);
    let ryzora_lock_path = home.join(RYZORA_LOCK_PATH);

    // Step 1: Write ryzora-lock wrapper
    write_ryzora_lock_wrapper(home)?;

    // Step 2: Compute source hash (before generating config)
    let source_hash = if source_path.exists() {
        sha256_file(&source_path)
            .unwrap_or_else(|| "unknown".to_string())
    } else {
        "no-source-found".to_string()
    };

    // Step 3: Generate Ryzora hypridle config
    let ryzora_config_dir = home.join(".config/ryzora");
    fs::create_dir_all(&ryzora_config_dir)
        .map_err(|e| format!("Failed to create ~/.config/ryzora: {}", e))?;

    let ryzora_config_path = home.join(HYPRIDLE_RYZORA_CONFIG);
    let config_content = if source_path.exists() {
        generate_ryzora_hypridle_config(&source_path, &ryzora_lock_path)?
    } else {
        // Source doesn't exist: generate minimal config
        format!(
            r#"# Ryzora-managed hypridle configuration (minimal — source not found)
general {{
    lock_cmd = pidof quickshell || {}
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}}
"#,
            ryzora_lock_path.display()
        )
    };

    fs::write(&ryzora_config_path, &config_content)
        .map_err(|e| format!("Failed to write Ryzora hypridle config: {}", e))?;

    // Step 4: Write systemd drop-in
    write_hypridle_systemd_dropin(home)?;

    // Step 5: Reload hypridle
    reload_hypridle_service()?;

    Ok((source_hash, ryzora_lock_path))
}

/// Deactivate the hypridle integration:
/// - Remove systemd drop-in
/// - Remove Ryzora hypridle config
/// - Reload hypridle (reverts to original config)
/// Does NOT remove ryzora-lock (it safely falls back to hyprlock when Ryzora is inactive)
pub fn deactivate_hypridle_integration(home: &Path) -> Result<(), String> {
    let dropin_path = home.join(HYPRIDLE_DROPIN_PATH);
    let ryzora_config_path = home.join(HYPRIDLE_RYZORA_CONFIG);

    // Remove drop-in
    if dropin_path.exists() {
        fs::remove_file(&dropin_path)
            .map_err(|e| format!("Failed to remove hypridle drop-in: {}", e))?;

        // Remove drop-in directory if empty
        if let Some(parent) = dropin_path.parent() {
            let _ = fs::remove_dir(parent); // Ignore error if not empty
        }
    }

    // Remove generated config
    if ryzora_config_path.exists() {
        fs::remove_file(&ryzora_config_path)
            .map_err(|e| format!("Failed to remove Ryzora hypridle config: {}", e))?;
    }

    // Reload hypridle → reverts to default config
    reload_hypridle_service()?;

    Ok(())
}

/// Check for configuration drift: compare stored source hash with current source hash.
/// Returns `Some(current_hash)` if drift detected, `None` if unchanged or no source.
pub fn check_hypridle_config_drift(
    home: &Path,
    stored_source_hash: &str,
) -> Option<String> {
    let source_path = home.join(HYPRIDLE_SOURCE_PATH);
    if !source_path.exists() {
        return None;
    }

    let current_hash = sha256_file(&source_path)?;
    if current_hash != stored_source_hash && stored_source_hash != "no-source-found" {
        Some(current_hash)
    } else {
        None
    }
}

/// Get the complete hypridle integration status
pub fn get_hypridle_integration_status(home: &Path, stored_hash: Option<&str>) -> HypridleIntegrationStatus {
    let lock_wrapper_path = home.join(RYZORA_LOCK_PATH);
    let ryzora_config_path = home.join(HYPRIDLE_RYZORA_CONFIG);
    let dropin_path = home.join(HYPRIDLE_DROPIN_PATH);
    let source_path = home.join(HYPRIDLE_SOURCE_PATH);

    let lock_wrapper_exists = lock_wrapper_path.exists();
    let ryzora_config_exists = ryzora_config_path.exists();
    let dropin_exists = dropin_path.exists();

    // Check if hypridle service is active (skip in test mode)
    let hypridle_service_active = if std::env::var("RYZORA_SYSTEM_ROOT").is_ok() {
        dropin_exists // In tests, assume active if drop-in exists
    } else {
        Command::new("systemctl")
            .args(["--user", "is-active", "--quiet", "hypridle"])
            .status()
            .map(|s| s.success())
            .unwrap_or(false)
    };

    let current_hash = sha256_file(&source_path);
    let drift_detected = if let (Some(stored), Some(current)) = (stored_hash, current_hash.as_deref()) {
        stored != current && stored != "no-source-found"
    } else {
        false
    };

    HypridleIntegrationStatus {
        lock_wrapper_exists,
        lock_wrapper_path,
        ryzora_config_exists,
        ryzora_config_path,
        dropin_exists,
        dropin_path,
        hypridle_service_active,
        source_hash: stored_hash.map(|s| s.to_string()),
        current_hash,
        drift_detected,
    }
}

/// Check if the user lock script exists and verify whether it delegates to ryzora-lock.
/// Returns true if no user lock script exists on the host (not required), or if it exists and delegates to ryzora-lock.
pub fn verify_user_lock_script_hook(home: &Path) -> bool {
    let target = home.join(USER_LOCK_SCRIPT_PATH);
    if !target.exists() {
        return true;
    }
    match fs::read_to_string(&target) {
        Ok(content) => content.contains("ryzora-lock") && content.contains("RYZORA_ACTIVE"),
        Err(_) => false,
    }
}

/// Hook the host user lock script (e.g. ~/user_scripts/hyprlock/lock.sh) so that manual
/// locking (SUPER + M, Waybar, wlogout) delegates to ryzora-lock when Ryzora is active.
///
/// If the script exists:
/// 1. Snapshots the original script to ~/.local/share/ryzora/snapshots/user_scripts_hyprlock_lock.sh verbatim.
/// 2. Writes a Ryzora dispatcher hook that executes ~/.local/bin/ryzora-lock when active,
///    and falls back to the original script content when inactive.
///
/// Returns Ok(Some((target_path, snapshot_path))) if hooked, or Ok(None) if target does not exist.
pub fn hook_user_lock_script(home: &Path) -> Result<Option<(PathBuf, PathBuf)>, String> {
    let target = home.join(USER_LOCK_SCRIPT_PATH);
    if !target.exists() {
        return Ok(None);
    }

    let snapshot = home.join(USER_LOCK_SCRIPT_SNAPSHOT);
    if let Some(parent) = snapshot.parent() {
        fs::create_dir_all(parent)
            .map_err(|e| format!("Failed to create snapshot directory for user lock script: {}", e))?;
    }

    let current_content = fs::read_to_string(&target)
        .map_err(|e| format!("Failed to read host lock script '{}': {}", target.display(), e))?;

    // If the target is NOT already hooked, snapshot it verbatim
    let original_content = if current_content.contains("# Ryzora session-lock hook") {
        if snapshot.exists() {
            fs::read_to_string(&snapshot)
                .map_err(|e| format!("Failed to read existing snapshot '{}': {}", snapshot.display(), e))?
        } else {
            current_content.clone()
        }
    } else {
        fs::write(&snapshot, &current_content)
            .map_err(|e| format!("Failed to write snapshot '{}': {}", snapshot.display(), e))?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let _ = fs::set_permissions(&snapshot, fs::Permissions::from_mode(0o755));
        }
        current_content.clone()
    };

    // Strip shebang from original content if present for fallback body
    let fallback_body = if original_content.starts_with("#!") {
        if let Some(newline_pos) = original_content.find('\n') {
            &original_content[newline_pos + 1..]
        } else {
            ""
        }
    } else {
        &original_content
    };

    let active_symlink = home.join(".local/share/ryzora/active/lockscreen/quickshell");
    let ryzora_lock = home.join(RYZORA_LOCK_PATH);

    let hooked_content = format!(
        r#"#!/usr/bin/env bash
# Ryzora session-lock hook — managed, do not edit
# Original script backed up verbatim by Ryzora at:
#   {snapshot_path}
RYZORA_ACTIVE="{active_symlink}"
RYZORA_LOCK="{ryzora_lock}"

if [ -L "$RYZORA_ACTIVE" ] && [ -d "$RYZORA_ACTIVE" ] && [ -x "$RYZORA_LOCK" ]; then
    exec "$RYZORA_LOCK"
fi

# --- Original Host Lock Script Fallback ---
{fallback_body}
"#,
        snapshot_path = snapshot.display(),
        active_symlink = active_symlink.display(),
        ryzora_lock = ryzora_lock.display(),
        fallback_body = fallback_body.trim_start(),
    );

    fs::write(&target, &hooked_content)
        .map_err(|e| format!("Failed to write hooked host lock script '{}': {}", target.display(), e))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = fs::set_permissions(&target, fs::Permissions::from_mode(0o755));
    }

    Ok(Some((target, snapshot)))
}

/// Unhook the user lock script and restore the original script verbatim from the snapshot.
pub fn unhook_user_lock_script(home: &Path) -> Result<(), String> {
    let target = home.join(USER_LOCK_SCRIPT_PATH);
    let snapshot = home.join(USER_LOCK_SCRIPT_SNAPSHOT);

    if snapshot.exists() {
        let original = fs::read_to_string(&snapshot)
            .map_err(|e| format!("Failed to read user lock script snapshot: {}", e))?;

        if let Some(parent) = target.parent() {
            let _ = fs::create_dir_all(parent);
        }

        fs::write(&target, &original)
            .map_err(|e| format!("Failed to restore host lock script '{}': {}", target.display(), e))?;

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let _ = fs::set_permissions(&target, fs::Permissions::from_mode(0o755));
        }

        let _ = fs::remove_file(&snapshot);
    } else if target.exists() {
        let content = fs::read_to_string(&target).unwrap_or_default();
        if content.contains("# Ryzora session-lock hook") {
            if let Some(pos) = content.find("# --- Original Host Lock Script Fallback ---") {
                let fallback = &content[pos + "# --- Original Host Lock Script Fallback ---".len()..];
                let restored = format!("#!/usr/bin/env bash
{}", fallback.trim_start());
                let _ = fs::write(&target, restored);
            }
        }
    }

    Ok(())
}

/// Launch the lockscreen test process detached.
pub fn launch_test_process(lock_sh: &Path) -> Result<(), String> {
    std::process::Command::new("bash")
        .arg(lock_sh.as_os_str())
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .spawn()
        .map_err(|e| format!("Failed to launch lockscreen test: {}", e))?;
    Ok(())
}

/// Launch Quickshell in isolated test mode for any specified theme directory.
/// Does not alter hypridle.conf, active symlinks, or persistent active state.
/// Launch SDDM greeter in isolated test mode for any specified theme directory.
pub fn launch_test_sddm_process(theme_dir: &Path) -> Result<(), String> {
    // Check available greeter binary
    let binary = if Path::new("/usr/bin/sddm-greeter-qt6").exists() {
        "sddm-greeter-qt6"
    } else if Path::new("/usr/bin/sddm-greeter").exists() {
        "sddm-greeter"
    } else {
        return Err("Neither 'sddm-greeter-qt6' nor 'sddm-greeter' was found in /usr/bin. Install SDDM to preview login themes.".to_string());
    };

    std::process::Command::new(binary)
        .arg("--test-mode")
        .arg("--theme")
        .arg(theme_dir.as_os_str())
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .spawn()
        .map_err(|e| format!("Failed to spawn SDDM greeter test: {}", e))?;
    Ok(())
}

pub fn launch_test_qml_process(lock_shell_qml: &Path, theme_dir: &Path) -> Result<(), String> {
    std::process::Command::new("quickshell")
        .arg("-p")
        .arg(lock_shell_qml.as_os_str())
        .env("QS_THEME_PATH", theme_dir)
        .env("QML_XHR_ALLOW_FILE_READ", "1")
        .env("XDG_SESSION_TYPE", std::env::var("XDG_SESSION_TYPE").unwrap_or_else(|_| "wayland".to_string()))
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .spawn()
        .map_err(|e| format!("Failed to spawn Quickshell test lockscreen: {}", e))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::sync::atomic::{AtomicU64, Ordering};

    static TEST_COUNTER: AtomicU64 = AtomicU64::new(0);

    fn test_home(name: &str) -> PathBuf {
        let id = TEST_COUNTER.fetch_add(1, Ordering::Relaxed);
        let p = std::env::temp_dir().join(format!("ryzora-hypridle-{}-{}", name, id));
        fs::create_dir_all(&p).unwrap();
        p
    }

    fn cleanup(p: &Path) {
        let _ = fs::remove_dir_all(p);
    }

    fn write_sample_hypridle(home: &Path) -> PathBuf {
        let hypr_dir = home.join(".config/hypr");
        fs::create_dir_all(&hypr_dir).unwrap();
        let conf = hypr_dir.join("hypridle.conf");
        fs::write(&conf, r#"
general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 140
    on-timeout = brightnessctl -sd asus::kbd_backlight set 0
    on-resume = brightnessctl -rd asus::kbd_backlight
}

listener {
    timeout = 2480
    on-timeout = loginctl lock-session
}
"#).unwrap();
        conf
    }

    #[test]
    fn test_generate_ryzora_hypridle_config_preserves_listeners() {
        let home = test_home("gen-config");
        let source = write_sample_hypridle(&home);
        let ryzora_lock = home.join(".local/bin/ryzora-lock");

        let generated = generate_ryzora_hypridle_config(&source, &ryzora_lock).unwrap();

        // Lock cmd must be replaced
        assert!(!generated.contains("pidof hyprlock || hyprlock"), "Old lock_cmd must be gone");
        assert!(generated.contains("ryzora-lock"), "ryzora-lock must be in generated config");

        // All listener blocks must be preserved
        assert!(generated.contains("brightnessctl -sd asus::kbd_backlight"), "listener 1 must be preserved");
        assert!(generated.contains("loginctl lock-session"), "listener 2 must be preserved");
        assert!(generated.contains("2480"), "timeout must be preserved");

        // Before/after sleep preserved
        assert!(generated.contains("before_sleep_cmd"), "before_sleep_cmd must be preserved");
        assert!(generated.contains("after_sleep_cmd"), "after_sleep_cmd must be preserved");

        cleanup(&home);
    }

    #[test]
    fn test_write_ryzora_lock_wrapper_creates_executable() {
        let _guard = crate::TEST_ENV_MUTEX.lock().unwrap_or_else(|p| p.into_inner());
        let home = test_home("lock-wrapper");
        std::env::set_var("RYZORA_SYSTEM_ROOT", &home); // test mode
        write_ryzora_lock_wrapper(&home).unwrap();

        let lock_path = home.join(RYZORA_LOCK_PATH);
        assert!(lock_path.exists(), "ryzora-lock must exist");

        let content = fs::read_to_string(&lock_path).unwrap();
        assert!(content.starts_with("#!/usr/bin/env bash"), "must be a bash script");
        assert!(content.contains("RYZORA_ACTIVE"), "must reference RYZORA_ACTIVE");
        assert!(content.contains("RYZORA_LOCK"), "must reference RYZORA_LOCK");
        assert!(!content.contains("eval"), "must not use eval");
        assert!(!content.contains("exec $"), "must not exec arbitrary vars");

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let perms = fs::metadata(&lock_path).unwrap().permissions();
            assert!(perms.mode() & 0o111 != 0, "ryzora-lock must be executable");
        }

        std::env::remove_var("RYZORA_SYSTEM_ROOT");
        cleanup(&home);
    }

    #[test]
    fn test_write_hypridle_systemd_dropin_resets_execstart() {
        let home = test_home("dropin");
        write_hypridle_systemd_dropin(&home).unwrap();

        let dropin_path = home.join(HYPRIDLE_DROPIN_PATH);
        assert!(dropin_path.exists(), "drop-in must exist");

        let content = fs::read_to_string(&dropin_path).unwrap();
        // MUST have empty ExecStart= reset BEFORE the new value
        let execstart_empty_pos = content.find("ExecStart=\n").unwrap_or(usize::MAX);
        let execstart_new_pos = content.find("ExecStart=/usr/bin/hypridle").unwrap_or(usize::MAX);
        assert!(
            execstart_empty_pos < execstart_new_pos,
            "ExecStart= reset must precede new ExecStart in drop-in"
        );
        assert!(content.contains("-c"), "Must pass -c flag to hypridle");
        assert!(content.contains("ryzora/hypridle.conf"), "Must reference Ryzora config");

        cleanup(&home);
    }

    #[test]
    fn test_sha256_changes_on_file_modification() {
        let home = test_home("sha256");
        let source = write_sample_hypridle(&home);

        let hash1 = sha256_file(&source).unwrap();
        // Modify file
        fs::write(&source, "# modified\n").unwrap();
        let hash2 = sha256_file(&source).unwrap();

        assert_ne!(hash1, hash2, "SHA-256 must change when file changes");

        cleanup(&home);
    }

    #[test]
    fn test_drift_detection_when_source_changes() {
        let home = test_home("drift");
        let source = write_sample_hypridle(&home);

        let original_hash = sha256_file(&source).unwrap();

        // Simulate Dusky changing the config
        fs::write(&source, "# Dusky changed this\ngeneral {\n    lock_cmd = hyprlock\n}\n").unwrap();

        let drift = check_hypridle_config_drift(&home, &original_hash);
        assert!(drift.is_some(), "Drift must be detected after source change");

        cleanup(&home);
    }

    #[test]
    fn test_no_drift_when_source_unchanged() {
        let home = test_home("no-drift");
        let source = write_sample_hypridle(&home);

        let original_hash = sha256_file(&source).unwrap();

        // No change to source
        let drift = check_hypridle_config_drift(&home, &original_hash);
        assert!(drift.is_none(), "No drift should be detected for unchanged source");

        cleanup(&home);
    }

    #[test]
    fn test_deactivate_removes_dropin_and_config() {
        let _guard = crate::TEST_ENV_MUTEX.lock().unwrap_or_else(|p| p.into_inner());
        let home = test_home("deactivate");
        std::env::set_var("RYZORA_SYSTEM_ROOT", &home); // skip systemctl in test

        // Write source config
        write_sample_hypridle(&home);

        // Write lock wrapper
        write_ryzora_lock_wrapper(&home).unwrap();

        // Write generated config
        let ryzora_config_dir = home.join(".config/ryzora");
        fs::create_dir_all(&ryzora_config_dir).unwrap();
        fs::write(home.join(HYPRIDLE_RYZORA_CONFIG), "# test").unwrap();

        // Write drop-in
        write_hypridle_systemd_dropin(&home).unwrap();

        // Verify they exist
        assert!(home.join(HYPRIDLE_DROPIN_PATH).exists());
        assert!(home.join(HYPRIDLE_RYZORA_CONFIG).exists());

        // Deactivate
        deactivate_hypridle_integration(&home).unwrap();

        // Drop-in and config must be removed
        assert!(!home.join(HYPRIDLE_DROPIN_PATH).exists(), "Drop-in must be removed on deactivate");
        assert!(!home.join(HYPRIDLE_RYZORA_CONFIG).exists(), "Ryzora config must be removed on deactivate");

        // ryzora-lock wrapper remains (it falls back safely)
        assert!(home.join(RYZORA_LOCK_PATH).exists(), "ryzora-lock must remain after deactivate");

        std::env::remove_var("RYZORA_SYSTEM_ROOT");
        cleanup(&home);
    }

    #[test]
    fn test_hook_and_unhook_user_lock_script_verbatim_restore() {
        let home = test_home("user-lock-hook");
        let script_dir = home.join("user_scripts/hyprlock");
        fs::create_dir_all(&script_dir).unwrap();
        let target = script_dir.join("lock.sh");
        let original_script = "#!/bin/bash\n# Sample Dusky hyprlock\nWALLPAPER=\"/tmp/bg.png\"\ncp \"$WALLPAPER\" ~/.cache/current_wallpaper\nhyprlock\n";
        fs::write(&target, original_script).unwrap();

        // 1. Hook
        let res = hook_user_lock_script(&home).unwrap();
        assert!(res.is_some());
        let (hooked_target, snapshot) = res.unwrap();
        assert_eq!(hooked_target, target);
        assert!(snapshot.exists(), "Snapshot must be created");

        // Verify hook content
        let hooked_content = fs::read_to_string(&target).unwrap();
        assert!(hooked_content.contains("Ryzora session-lock hook"));
        assert!(hooked_content.contains("RYZORA_ACTIVE"));
        assert!(hooked_content.contains("RYZORA_LOCK"));
        assert!(hooked_content.contains("hyprlock"), "Fallback hyprlock command preserved");

        // Verify helper
        assert!(verify_user_lock_script_hook(&home));

        // 2. Unhook
        unhook_user_lock_script(&home).unwrap();
        assert!(!snapshot.exists(), "Snapshot must be cleaned up on unhook");

        // Verify verbatim restoration
        let restored_content = fs::read_to_string(&target).unwrap();
        assert_eq!(restored_content, original_script, "Restored content must match original verbatim");

        cleanup(&home);
    }

    #[test]
    fn test_apply_integration_end_to_end() {
        let _guard = crate::TEST_ENV_MUTEX.lock().unwrap_or_else(|p| p.into_inner());
        let home = test_home("apply-e2e");
        std::env::set_var("RYZORA_SYSTEM_ROOT", &home);

        // Write source config (simulating Dusky's hypridle.conf)
        write_sample_hypridle(&home);

        let (source_hash, _lock_path) = apply_hypridle_integration(&home).unwrap();

        // All artifacts must exist
        assert!(home.join(RYZORA_LOCK_PATH).exists(), "ryzora-lock must exist");
        assert!(home.join(HYPRIDLE_RYZORA_CONFIG).exists(), "Ryzora config must exist");
        assert!(home.join(HYPRIDLE_DROPIN_PATH).exists(), "drop-in must exist");

        // Source hash recorded
        assert!(!source_hash.is_empty());
        assert_ne!(source_hash, "unknown");

        // Verify Dusky's original file was NOT modified
        let source_path = home.join(HYPRIDLE_SOURCE_PATH);
        let original_hash = sha256_file(&source_path).unwrap();
        assert_eq!(source_hash, original_hash, "Stored hash must match source (source was not modified)");

        std::env::remove_var("RYZORA_SYSTEM_ROOT");
        cleanup(&home);
    }
}
